config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'

  resources :messages
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :body, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, -> { order(:id) }
  has_many :users, through: :messages

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages

  validates_uniqueness_of :user_name

  def self.generate
    names = ['Thor', 'Loki', 'Odin', 'Hela', 'Hulk', 'Thanos', 'Tony-Stark', 'Black-Widow', 'Zeus', 'Hercules', 'Gorr']
    funds = ['Jump-Trading', 'A16z', 'Multicoin-Capital', 'Paradigm', 'Polychain-Capital', 'DWF-Labs']

    user_name = "#{ names.sample }-#{ funds.sample }-#{ rand(100000..999999) }"
    create(user_name: user_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    return @current_user if @current_user.present?

    if cookies[:user_id].present?
      @current_user = User.find(cookies[:user_id])
    else
      @current_user = User.generate
    end

    cookies[:user_id] = @current_user.id

    @current_user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = Message.new(message_params)
    message.user = current_user
    message.save if message.valid?

    SendMessageJob.perform_later(message)
  end

  private

  def message_params
    params.require(:message).permit(:room_id, :body)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :load_room, only: :show

  def index
    @rooms = Room.all
  end

  def show
    @rooms    = Room.all
    @messages = @room.messages.includes(:user)

    render :index
  end

  def create
    room = Room.new(room_params)

    if room.valid? && room.save
      @rooms = Room.all
      return render :index
    end

    redirect_to request.referer
  end

  private

  def load_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatRoom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: false) do |f| %>
  <%= f.hidden_field :room_id, value: room.id %>

  <div class="input-group">
    <%= f.text_area :body, placeholder: "Type your message...", autocomplete: "off", class: "form-control" %>

    <div class="input-group-append">
      <button type="submit" class="btn btn-primary px-4">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send-fill" viewBox="0 0 16 16">
          <path d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471z"/>
        </svg>
        Send
      </button>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="message mb-3 <%= "me" if message.user == current_user %>">
  <div class="content-container">
    <div class="content">
      <span><%= message.body %></span>
    </div>

    <div class="sender text-secondary">
      <span class="js-user-<%= message.user_id %>-status activity-status">•</span>
      <%= message.user.user_name %>
    </div>
  </div>
</div>

app/views/messages/_mine.html.erb
<div class="message mb-3 me">
  <div class="content-container">
    <div class="content">
      <span><%= message.body %></span>
    </div>

    <div class="sender text-secondary">
      <span class="js-user-<%= message.user_id %>-status activity-status online">•</span>
      <%= message.user.user_name %>
    </div>
  </div>
</div>

app/views/messages/_theirs.html.erb
<div class="message mb-3">
  <div class="content-container">
    <div class="content">
      <span><%= message.body %></span>
    </div>

    <div class="sender text-secondary">
      <span class="js-user-<%= message.user_id %>-status activity-status online">•</span>
      <%= message.user.user_name %>
    </div>
  </div>
</div>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :name, "New Room" %>
    <%= f.text_field :name, placeholder: "Room name", autocomplete: "off", class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-outline-primary form-control" %>
<% end %>

app/views/rooms/index.html.erb
<div id="js-room-id" data-room-id="<%= @room&.id %>"></div>
<div id="js-user-id" data-user-id="<%= current_user.id %>"></div>

<div class="cointainer-fluid">
  <div class="row">
    <div class="col-3 rooms-sidebar">

      <div class="card border-0 mb-5">
        <div class="card-body">
          <small>Logged in as</small>
          <b class="text-primary"><%= current_user.user_name %></b>
        </div>
      </div>

      <%= render 'form', room: Room.new %>
      <hr>

      <% @rooms.each do |room| %>
        <%= link_to room_path(room.id), class: 'room-link' do %>
          <div class="card room-card border-0 mb-1 <%= 'active' if room == @room %>">
            <div class="card-body">
              <b class="room-name"><%= room.name %></b>
              <br>
              <small class="room-members"><%= room.users.pluck(:id).uniq.count %> members</small>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="col-9">
      <% if @room.present? %>
        <div class="chat-room">
          <nav class="navbar navbar-light">
            <b class="navbar-brand"><%= @room.name %></b>
            <small><%= @room.users.pluck(:id).uniq.count %> members</small>
          </nav>

          <div id="js-messages-container" class="messages-area">
            <%= render partial: 'messages/message', collection: @messages %>
          </div>

          <div class="chat-box">
            <%= render 'messages/form', room: @room, message: Message.new %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>